In [142]:
import pandas as pd

In [143]:
meta_score = pd.read_excel("C:/Users/Emma/Desktop/metaClean43Brightspace.xlsx")
movie_table = pd.read_csv("C:/Users/Emma/Downloads/movies_table.csv")
actor_table = pd.read_csv("C:/Users/Emma/Downloads/actors.csv")

In [144]:
meta_score.head()

,url,title,studio,rating,runtime,cast,director,genre,summary,awards,metascore,userscore,RelDate
0,https://www.metacritic.com/movie/!women-art-re...,!Women Art Revolution,Hotwire Productions,| Not Rated,83.0,NaN,Lynn Hershman-Leeson,Documentary,NaN,NaN,70,NaN,2011-06-01
1,https://www.metacritic.com/movie/10-cloverfiel...,10 Cloverfield Lane,Paramount Pictures,| PG-13,104.0,"John Gallagher Jr.,John Goodman,Mary Elizabeth...",Dan Trachtenberg,"Action,Sci-Fi,Drama,Mystery,Thriller,Horror","Waking up from a car accident, a young woman (...","#18MostDiscussedMovieof2016 , #1MostSharedMovi...",76,7.7,2016-03-11
2,https://www.metacritic.com/movie/10-items-or-less,10 Items or Less,Click Star,| R,82.0,"Jonah Hill,Morgan Freeman,Paz Vega",Brad Silberling,"Drama,Comedy,Romance",While researching a role as a supermarket mana...,NaN,54,5.8,2006-12-01
3,https://www.metacritic.com/movie/10-years,10 Years,Anchor Bay Entertainment,| R,100.0,"Channing Tatum,Chris Pratt,Jenna Dewan",Jamie Linden,"Drama,Comedy,Romance",NaN,NaN,61,6.9,2012-09-14
4,https://www.metacritic.com/movie/100-bloody-acres,100 Bloody Acres,Music Box Films,| Not Rated,91.0,NaN,Cameron Cairnes,"Horror,Comedy",Reg and Lindsay run an organic fertilizer busi...,NaN,63,7.5,2013-06-28

In [145]:
#splits the string values into lists separated by comma
meta_score["cast"] = meta_score["cast"].str.split(",")
meta_score["awards"] = meta_score["awards"].str.split(",")

In [146]:
#creates new dataframe for the relationship table
movie_actor = pd.DataFrame(columns = ["url", "actor_name"])

In [147]:
movie_actor["url"] = meta_score["url"]
movie_actor["actor_name"] = meta_score["cast"]

In [148]:
movie_actor.head()

,url,actor_name
0,https://www.metacritic.com/movie/!women-art-re...,NaN
1,https://www.metacritic.com/movie/10-cloverfiel...,"[John Gallagher Jr., John Goodman, Mary Elizab..."
2,https://www.metacritic.com/movie/10-items-or-less,"[Jonah Hill, Morgan Freeman, Paz Vega]"
3,https://www.metacritic.com/movie/10-years,"[Channing Tatum, Chris Pratt, Jenna Dewan]"
4,https://www.metacritic.com/movie/100-bloody-acres,NaN

In [149]:
#expands the created lists into rows
movie_actor = movie_actor.explode("actor_name")
#normalises the data entires
movie_actor["actor_name"] = movie_actor["actor_name"].astype(str)
movie_actor["actor_name"] = movie_actor["actor_name"].str.lower()

In [150]:
movie_actor.head()

                                                 url               actor_name
0  https://www.metacritic.com/movie/!women-art-re...                      NaN
1  https://www.metacritic.com/movie/10-cloverfiel...       john gallagher jr.
1  https://www.metacritic.com/movie/10-cloverfiel...             john goodman
1  https://www.metacritic.com/movie/10-cloverfiel...  mary elizabeth winstead
2  https://www.metacritic.com/movie/10-items-or-less               jonah hill

In [151]:
#merges the combined table movie_actor with actor table based on the actor name
movie_actor = movie_actor.merge(actor_table, on="actor_name")

In [152]:
movie_actor.head()

,url,actor_name,actor_id
0,https://www.metacritic.com/movie/!women-art-re...,NaN,17601
1,https://www.metacritic.com/movie/10-cloverfiel...,john gallagher jr.,11722
2,https://www.metacritic.com/movie/10-cloverfiel...,john goodman,11730
3,https://www.metacritic.com/movie/10-cloverfiel...,mary elizabeth winstead,16025
4,https://www.metacritic.com/movie/10-items-or-less,jonah hill,11938

In [153]:
movie_actor = movie_actor.drop("actor_name", axis=1)

In [154]:
#merges the combined table movie_actor with movie  table based on the url
movie_actor = movie_actor.merge(movie_table, on="url")

In [155]:
#removes the unnecessary columns
movie_actor = movie_actor.drop(columns=['url', 'movie_name', 'RelDate', 'runtime', 'rating','summary', 'userscore', 'metascore'])

In [156]:
movie_actor

       actor_id  movie_id
0         17601     15294
1         11722     17335
2         11730     17335
3         16025     17335
4         11938     30220
...         ...       ...
51367      5043      4466
51368     23138      4466
51369     17601     33975
51370     17601     33976
51371     17601     21848

[51372 rows x 2 columns]

In [157]:
#sorts the movie_actor table asc based on movie id
movie_actor= movie_actor.sort_values(by = "movie_id")

In [158]:
movie_actor.head()

       actor_id  movie_id
3420      20731         2
3421      23177         2
32098     17601         3
1530      21517         5
1529      15394         5

In [159]:
#resets the index and creates a new id for movie-actor combination
movie_actor.reset_index(drop=True, inplace=True)
movie_actor["movie_actor_id"] = movie_actor.index + 1

In [160]:
movie_actor.head()

   actor_id  movie_id  movie_actor_id
0     20731         2               1
1     23177         2               2
2     17601         3               3
3     21517         5               4
4     15394         5               5

In [161]:
#movie_actor.to_csv("C:/Users/Emma/Downloads/movie_actor.csv",index = False)