In [125]:
import pandas as pd

In [126]:
meta_score = pd.read_excel("C:/Users/Emma/Desktop/metaClean43Brightspace.xlsx")
movie_table = pd.read_csv("C:/Users/Emma/Downloads/movies_table.csv")
studio_table = pd.read_csv("C:/Users/Emma/Downloads/studios.csv")

In [127]:
#splits the string values into lists separated by comma
meta_score["cast"] = meta_score["cast"].str.split(",")
meta_score["awards"] = meta_score["awards"].str.split(",")

In [128]:
#creates new dataframe for the relationship table
movie_studio = pd.DataFrame(columns = ["url", "studio_name"])

In [129]:
movie_studio["url"] = meta_score["url"]
movie_studio["studio_name"] = meta_score["studio"]

In [130]:
#normalises the data entries
movie_studio["studio_name"] = movie_studio["studio_name"].astype(str)
movie_studio["studio_name"] = movie_studio["studio_name"].str.lower()

In [131]:
movie_studio.head()

                                                 url               studio_name
0  https://www.metacritic.com/movie/!women-art-re...       hotwire productions
1  https://www.metacritic.com/movie/10-cloverfiel...        paramount pictures
2  https://www.metacritic.com/movie/10-items-or-less                click star
3          https://www.metacritic.com/movie/10-years  anchor bay entertainment
4  https://www.metacritic.com/movie/100-bloody-acres           music box films

In [132]:
#merges the combined table movie_director with director table based on the director name
movie_studio = movie_studio.merge(studio_table, on="studio_name")

In [133]:
movie_studio = movie_studio.drop("studio_name", axis=1)

In [134]:
movie_studio.head()

                                                 url  studio_id
0  https://www.metacritic.com/movie/!women-art-re...        501
1  https://www.metacritic.com/movie/10-cloverfiel...        782
2  https://www.metacritic.com/movie/10-items-or-less        249
3          https://www.metacritic.com/movie/10-years         71
4  https://www.metacritic.com/movie/100-bloody-acres        694

In [135]:
movie_studio = movie_studio.merge(movie_table, on="url")

In [136]:
movie_studio.head()

,url,studio_id,movie_id,movie_name,RelDate,runtime,rating,summary,userscore,metascore
0,https://www.metacritic.com/movie/!women-art-re...,501,15294,women art revolution,2011-06-01,83.0,| Not Rated,NaN,NaN,70.0
1,https://www.metacritic.com/movie/10-cloverfiel...,782,17335,10 cloverfield lane,2016-03-11,104.0,| PG-13,"Waking up from a car accident, a young woman (...",7.7,76.0
2,https://www.metacritic.com/movie/10-items-or-less,249,30220,10 items or less,2006-12-01,82.0,| R,While researching a role as a supermarket mana...,5.8,54.0
3,https://www.metacritic.com/movie/10-years,71,10828,10 years,2012-09-14,100.0,| R,NaN,6.9,61.0
4,https://www.metacritic.com/movie/100-bloody-acres,694,13304,100 bloody acres,2013-06-28,91.0,| Not Rated,Reg and Lindsay run an organic fertilizer busi...,7.5,63.0

In [137]:
#removes the unnecessary columns
movie_studio = movie_studio.drop(columns=['url', 'movie_name', 'RelDate', 'runtime', 'rating','summary', 'userscore', 'metascore'])

In [138]:
#sorts the movie_director table asc based on movie id
movie_studio = movie_studio.sort_values(by = "movie_id")

In [139]:
movie_studio

       studio_id  movie_id
751          655         2
6896         722         3
348         1081         5
8802         511        10
5070         755        11
...          ...       ...
10905        257     33972
10908        782     33973
10909        782     33974
10911        888     33975
10912       1077     33976

[10914 rows x 2 columns]

In [140]:
#resets the index and creates a new id for movie-director combination
movie_studio.reset_index(drop=True, inplace=True)
movie_studio["movie_studio_id"] = movie_studio.index + 1

In [141]:
movie_studio.head()

   studio_id  movie_id  movie_studio_id
0        655         2                1
1        722         3                2
2       1081         5                3
3        511        10                4
4        755        11                5

In [142]:
#movie_studio.to_csv("C:/Users/Emma/Downloads/movie_studio.csv",index = False)