In [83]:
import pandas as pd

In [84]:
meta_score = pd.read_excel("C:/Users/Emma/Desktop/metaClean43Brightspace.xlsx")
movie_table = pd.read_csv("C:/Users/Emma/Downloads/movies_table.csv")
director_table = pd.read_csv("C:/Users/Emma/Downloads/directors.csv")

In [85]:
#creates new dataframe for the relationship table
movie_director = pd.DataFrame(columns = ["url", "director_name"])

In [86]:
movie_director["url"] = meta_score["url"]
movie_director["director_name"] = meta_score["director"]

In [87]:
#normalises the data enrty
movie_director["director_name"] = movie_director["director_name"].astype(str)
movie_director["director_name"] = movie_director["director_name"].str.lower()

In [88]:
director_table

      director_id                 director_name
0               1                  a. dean bell
1               2                   a.b. shawky
2               3                    a.j. eaton
3               4                  a.j. edwards
4               5                   aaron aites
...           ...                           ...
6131         6132  ãsa helga hjã¶rleifsdã³ttir
6132         6133            ãlã©onore faucher
6133         6134             ãmile gaudreault
6134         6135               ãtienne sauret
6135         6136                  ãva gã¡rdos

[6136 rows x 2 columns]

In [ ]:
#merges the combined table movie_director with director table based on the director name
movie_director = movie_director.merge(director_table, on="director_name")

In [90]:
movie_director = movie_director.drop("director_name", axis=1)

In [91]:
movie_director.head()

                                                 url  director_id
0  https://www.metacritic.com/movie/!women-art-re...         3798
1  https://www.metacritic.com/movie/10-cloverfiel...         1379
2  https://www.metacritic.com/movie/10-items-or-less          804
3          https://www.metacritic.com/movie/10-years         2640
4  https://www.metacritic.com/movie/100-bloody-acres          927

In [92]:
#merges the combined table movie_director with movie  table based on the url
movie_director = movie_director.merge(movie_table, on="url")

In [93]:
#removes the unnecessary columns
movie_director = movie_director.drop(columns=['url', 'movie_name', 'RelDate', 'runtime', 'rating','summary', 'userscore', 'metascore'])

In [94]:
movie_director

       director_id  movie_id
0             3798     15294
1             1379     17335
2              804     30220
3             2640     10828
4              927     13304
...            ...       ...
11244          662     33974
11245         4742      4466
11246         4703     33975
11247          918     33976
11248         4694     21848

[11249 rows x 2 columns]

In [ ]:
#sorts the movie_director table asc based on movie id
movie_director = movie_director.sort_values(by = "movie_id")

In [96]:
movie_director

       director_id  movie_id
777           4743         2
7118           167         3
363             74         5
9074           380        10
5233           924        11
...            ...       ...
11240         5183     33972
11243          662     33973
11244          662     33974
11246         4703     33975
11247          918     33976

[11249 rows x 2 columns]

In [ ]:
#resets the index and creates a new id for movie-director combination
movie_director.reset_index(drop=True, inplace=True)
movie_director["movie_director_id"] = movie_director.index + 1

In [98]:
movie_director.head()

   director_id  movie_id  movie_director_id
0         4743         2                  1
1          167         3                  2
2           74         5                  3
3          380        10                  4
4          924        11                  5

In [99]:
#movie_director.to_csv("C:/Users/Emma/Downloads/movie_director.csv",index = False)